# Generated by Django 3.0.3 on 2020-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.TextField(blank=True, null=True)),
                ('down_exp', models.TextField(blank=True, db_column='Down', null=True)),
            ],
            options={
                'db_table': 'Down_exp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.TextField(blank=True, null=True)),
                ('up_exp', models.TextField(blank=True, db_column='Up', null=True)),
            ],
            options={
                'db_table': 'Up_exp',
                'managed': False,
            },
        ),
    ]
